In [56]:
import pandas as pd
data=pd.read_csv("https://raw.githubusercontent.com/aniruddhachoudhury/Red-Wine-Quality/master/winequality-red.csv")

In [57]:
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [58]:
data.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [59]:
data.quality.unique()

array([5, 6, 7, 4, 8, 3])

In [60]:
data["quality"].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [61]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [62]:
data.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [63]:
X=data.drop("quality",axis=1)

In [64]:
y=data["quality"]


In [65]:
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [66]:
y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [68]:
X_train.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
548            12.4             0.350         0.49             2.6      0.079   
355             6.7             0.750         0.01             2.4      0.078   
1296            6.6             0.630         0.00             4.3      0.093   
209            11.0             0.300         0.58             2.1      0.054   
140             8.4             0.745         0.11             1.9      0.090   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
548                  27.0                  69.0  0.99940  3.12       0.75   
355                  17.0                  32.0  0.99550  3.55       0.61   
1296                 51.0                  77.5  0.99558  3.20       0.45   
209                   7.0                  19.0  0.99800  3.31       0.88   
140                  16.0                  63.0  0.99650  3.19       0.82   

      alcohol  
548      10.4  
355      12.8  
1296      9.5  
209      10.5  
140       9.6

In [69]:
 from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [70]:
scaler.fit(X_train)##calculate the mean and std dev

StandardScaler()

In [71]:
print(scaler.mean_)

[ 8.30345472  0.53246499  0.26933707  2.54691877  0.08772736 15.91223156
 46.76330532  0.99677933  3.31453782  0.65881419 10.41521942]


In [72]:
X_train_tf=scaler.transform(X_train)
X_train_tf

array([[ 2.40069523, -1.03103722,  1.12742595, ..., -1.26096312,
         0.52726134, -0.01431863],
       [-0.93967131,  1.22920403, -1.32502245, ...,  1.52622836,
        -0.28225704,  2.24363201],
       [-0.99827424,  0.55113165, -1.37611513, ..., -0.74241587,
        -1.20742091, -0.86105011],
       ...,
       [-0.6466567 ,  0.49462562, -1.06955908, ...,  1.26695473,
        -0.68701624, -0.86105011],
       [-0.23643625, -1.87862768,  0.4121285 , ...,  0.03540501,
         0.81637505,  1.39690052],
       [-1.46709761, -1.3700734 , -0.04770558, ...,  0.48913386,
        -0.68701624,  2.90220094]])

In [73]:
from sklearn.svm import SVC
model=SVC()

In [74]:
model.fit(X_train_tf,y_train)

SVC()

In [75]:
model.score(X_train_tf,y_train)

0.6778711484593838

In [76]:
X_test_tf=scaler.transform(X_test)

In [77]:
y_predict=model.predict(X_test_tf)

In [78]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predict)

0.5984848484848485

In [79]:
from sklearn.linear_model import LogisticRegression

In [80]:
model2=LogisticRegression()

In [81]:
model2.fit(X_train_tf,y_train)

LogisticRegression()

In [82]:
y_predict2=model2.predict(X_test_tf)

In [83]:
accuracy_score(y_test,y_predict2)

0.571969696969697

In [84]:
X_test_tf[0]

array([-0.3536421 ,  0.15558944, -0.96737373, -0.03334372,  0.55556956,
       -0.18596079, -0.02314512,  0.1740298 , -0.48314224,  0.00685666,
       -0.76696884])

In [85]:
model.predict([[-0.3536421 ,  0.15558944, -0.96737373, -0.03334372,  0.55556956,
       -0.18596079, -0.02314512,  0.1740298 , -0.48314224,  0.00685666,
       -0.76696884]])

array([5])

In [88]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
svc = svm.SVC()

# finding the best parameters for the SVC model

param = {
    'C': [0.8,0.9,1,1.1,1.2,1.3,1.4],
    'kernel':['linear', 'rbf'],
    'gamma' :[0.1,0.8,0.9,1,1.1,1.2,1.3,1.4]
}
grid_svc = GridSearchCV(model, param_grid = param, scoring = 'accuracy', cv = 10)
grid_svc.fit(X_train_tf, y_train)


/opt/conda/lib/python3.10/site-packages/sklearn/model_selection/_split.py:684: UserWarning: The least populated class in y has only 8 members, which is less than n_splits=10.
  warnings.warn(


GridSearchCV(cv=10, estimator=SVC(),
             param_grid={'C': [0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4],
                         'gamma': [0.1, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4],
                         'kernel': ['linear', 'rbf']},
             scoring='accuracy')

In [90]:

grid_svc.best_params_
     

{'C': 1.2, 'gamma': 0.8, 'kernel': 'rbf'}

In [95]:
# creating a new SVC model with these best parameters
from sklearn.metrics import classification_report, confusion_matrix

model2 = SVC(C = 1.2, gamma = 0.8, kernel = 'rbf')
model2.fit(X_train_tf, y_train)
y_pred = model2.predict(X_test_tf)

print(classification_report(y_test, y_predict2))
     

              precision    recall  f1-score   support

           3       0.50      0.50      0.50         2
           4       1.00      0.05      0.10        19
           5       0.64      0.76      0.69       217
           6       0.52      0.56      0.54       213
           7       0.44      0.24      0.31        70
           8       0.00      0.00      0.00         7

    accuracy                           0.57       528
   macro avg       0.52      0.35      0.36       528
weighted avg       0.57      0.57      0.55       528



/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [97]:
accuracy_score(y_test,y_pred)

0.6231060606060606

In [18]:
#gridsearch CV
df=pd.read_csv("https://raw.githubusercontent.com/srinivasav22/Graduate-Admission-Prediction/master/Admission_Predict_Ver1.1.csv")

In [19]:
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [20]:
df.columns


Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [26]:
#defining dependent and independent variables
X=df.iloc[:, :-1]

In [27]:
y=df.iloc[:,-1]

In [28]:
X.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  
0         1  
1         1  
2         1  
3         1  
4         0

In [29]:
y.head()

0    0.92
1    0.76
2    0.72
3    0.80
4    0.65
Name: Chance of Admit , dtype: float64

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.33, random_state=42)

In [33]:
X_train.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
471         472        311          103                  3  2.0   4.0  8.09   
26           27        322          109                  5  4.5   3.5  8.80   
7             8        308          101                  2  3.0   4.0  7.90   
453         454        319          103                  3  2.5   4.0  8.76   
108         109        331          116                  5  5.0   5.0  9.38   

     Research  
471         0  
26          0  
7           0  
453         1  
108         1

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Serial No.         500 non-null    int64  
 1   GRE Score          500 non-null    int64  
 2   TOEFL Score        500 non-null    int64  
 3   University Rating  500 non-null    int64  
 4   SOP                500 non-null    float64
 5   LOR                500 non-null    float64
 6   CGPA               500 non-null    float64
 7   Research           500 non-null    int64  
 8   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB


In [35]:
df.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  500.000000  500.000000   500.000000         500.000000  500.000000   
mean   250.500000  316.472000   107.192000           3.114000    3.374000   
std    144.481833   11.295148     6.081868           1.143512    0.991004   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    125.750000  308.000000   103.000000           2.000000    2.500000   
50%    250.500000  317.000000   107.000000           3.000000    3.500000   
75%    375.250000  325.000000   112.000000           4.000000    4.000000   
max    500.000000  340.000000   120.000000           5.000000    5.000000   

            LOR         CGPA    Research  Chance of Admit   
count  500.00000  500.000000  500.000000         500.00000  
mean     3.48400    8.576440    0.560000           0.72174  
std      0.92545    0.604813    0.496884           0.14114  
min      1.00000    6.800000    0.000000           0.34000  
25%      3.00000    8.127500    0.000000           0.63000  
50%      3.50000    8.560000    1.000000           0.72000  
75%      4.00000    9.040000    1.000000           0.82000  
max      5.00000    9.920000    1.000000           0.97000

In [37]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train_tf=scaler.transform(X_train)
X_train_tf

array([[ 1.55816388e+00, -5.25174731e-01, -7.06985745e-01, ...,
         5.38819022e-01, -8.35765678e-01, -1.14470294e+00],
       [-1.64243247e+00,  4.77035981e-01,  2.76433873e-01, ...,
        -1.61323061e-03,  3.63045482e-01, -1.14470294e+00],
       [-1.77908715e+00, -7.98504925e-01, -1.03479228e+00, ...,
         5.38819022e-01, -1.15657430e+00, -1.14470294e+00],
       ...,
       [ 6.73504661e-01, -1.34516531e+00, -1.36259882e+00, ...,
        -1.62290999e+00, -2.25407747e+00, -1.14470294e+00],
       [ 1.29923923e+00, -7.07394861e-01, -3.79179206e-01, ...,
         5.38819022e-01, -1.52803691e+00, -1.14470294e+00],
       [-1.09581377e+00, -2.51844537e-01, -2.15275936e-01, ...,
        -1.61323061e-03, -5.65611050e-01, -1.14470294e+00]])

In [40]:
from sklearn.svm import SVR
model=SVR()
model.fit(X_train_tf, y_train)

SVR()

In [42]:
X_test_tf=scaler.transform(X_test)
y_predict=model.predict(X_test_tf)


In [43]:
y_predict

array([0.85327566, 0.70566642, 0.56577617, 0.68513912, 0.73073652,
       0.84759115, 0.50884113, 0.63512354, 0.71546806, 0.75966639,
       0.57183244, 0.71682881, 0.6228902 , 0.87034528, 0.80538203,
       0.45539152, 0.78034293, 0.51298148, 0.52072102, 0.57781496,
       0.65704711, 0.53857913, 0.7306496 , 0.78872557, 0.69357076,
       0.5926933 , 0.843987  , 0.82839114, 0.59525329, 0.75285329,
       0.56177445, 0.761017  , 0.57579346, 0.84035618, 0.57955442,
       0.7686765 , 0.50127929, 0.88017372, 0.66595737, 0.64142824,
       0.87065485, 0.52080723, 0.63350483, 0.85528765, 0.82310479,
       0.47790267, 0.85620031, 0.74364715, 0.76326758, 0.85361512,
       0.81739371, 0.55214794, 0.6810001 , 0.53159075, 0.90702514,
       0.56836681, 0.83980413, 0.59580852, 0.6745631 , 0.45741035,
       0.59644739, 0.72846957, 0.5933817 , 0.62610304, 0.48959131,
       0.54214166, 0.83976541, 0.8396225 , 0.67509268, 0.69812838,
       0.65151703, 0.79682174, 0.69471546, 0.58558049, 0.51274

In [46]:

#performance metrics
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
print(mean_squared_error(y_test,y_predict))
print(mean_absolute_error(y_test,y_predict))
print(np.sqrt(mean_squared_error(y_test,y_predict)))


0.004878474514395206
0.05626497201211845
0.06984607730141476


In [47]:
## R square and adjusted R square
from sklearn.metrics import r2_score
score=r2_score(y_test,y_predict)
print(score)


0.7632199437959383
